"""Moving is active to user table

Revision ID: dae575f4dd5d
Revises: 95e6e9ef7e69
Create Date: 2025-11-30 23:28:03.855876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dae575f4dd5d"
down_revision: Union[str, Sequence[str], None] = "95e6e9ef7e69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "is_active")
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.add_column(
        "profiles",
        sa.Column(
            "is_active", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###